# Generated by Django 3.1.7 on 2021-02-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('imageresizer', '0002_auto_20210222_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newimage',
            name='image',
            field=models.ImageField(blank=True, height_field='100', upload_to='', verbose_name='Файл',
                                    width_field='100'),
        ),
    ]
