# Generated by Django 3.1.7 on 2021-02-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageresizer', '0005_remove_newimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newimage',
            name='resized_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Файл'),
        ),
    ]
